#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# scripts/build-android-release.sh
# §5.2 Android cell — universal APK + per-ABI APKs + AAB + Rust .so for 4 ABIs
# ══════════════════════════════════════════════════════════════════════════════
set -x; set -e; set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VERSION="9.0.0-enterprise"
REL="release/${VERSION}"
mkdir -p "${REL}/apk" "${REL}/aab"

# ── Required environment / tools ─────────────────────────────────────────────
command -v cargo   >/dev/null || { echo "::error::cargo missing"; exit 1; }
command -v rustup  >/dev/null || { echo "::error::rustup missing"; exit 1; }
command -v flutter >/dev/null || { echo "::error::flutter missing"; exit 1; }

# Optional: prefer `cross` for Android NDK cross-compilation
CROSS_BIN="cross"
if ! command -v "$CROSS_BIN" >/dev/null 2>&1; then
  CROSS_BIN="cargo"
  echo "::warning::cross not found, falling back to cargo (Android NDK must be on PATH)"
fi

# ── Auto-configure cargo NDK linkers when using plain cargo ──────────────────
# On GitHub Actions runners the NDK lives under $ANDROID_HOME/ndk/<ver>; plain
# cargo cannot link Android targets without per-target linker entries. This
# writes ~/.cargo/config.toml automatically (idempotent, CI-safe).
if [ "$CROSS_BIN" = "cargo" ]; then
  SDK_ROOT="${ANDROID_HOME:-/usr/local/lib/android/sdk}"
  NDK_DIR="$(ls -d "${SDK_ROOT}"/ndk/* 2>/dev/null | sort -V | tail -1 || true)"
  if [ -n "$NDK_DIR" ] && [ -d "$NDK_DIR" ]; then
    TOOLCHAIN="${NDK_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin"
    if [ -d "$TOOLCHAIN" ]; then
      echo "==[ Wiring cargo linkers to NDK toolchain: ${NDK_DIR} ]=="
      mkdir -p "$HOME/.cargo"
      cat > "$HOME/.cargo/config.toml" <<EOF
# AUTO-GENERATED by scripts/build-android-release.sh (CI)
[target.aarch64-linux-android]
linker = "${TOOLCHAIN}/aarch64-linux-android24-clang"
[target.armv7-linux-androideabi]
linker = "${TOOLCHAIN}/armv7a-linux-androideabi24-clang"
[target.i686-linux-android]
linker = "${TOOLCHAIN}/i686-linux-android24-clang"
[target.x86_64-linux-android]
linker = "${TOOLCHAIN}/x86_64-linux-android24-clang"
EOF
    fi
  else
    echo "::warning::No Android NDK found under ${SDK_ROOT} — Rust Android build may fail to link"
  fi
fi

# ── Android ABIs and matching Rust targets ────────────────────────────────────
ANDROID_ABIS=(arm64-v8a armeabi-v7a x86 x86_64)
RUST_TARGETS=(aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android)

# Ensure Rust targets are installed
for t in "${RUST_TARGETS[@]}"; do
  rustup target add "$t" >/dev/null 2>&1 || true
done

# ── Cross-compile Rust daemon for each Android ABI ────────────────────────────
for i in "${!ANDROID_ABIS[@]}"; do
  abi="${ANDROID_ABIS[$i]}"
  target="${RUST_TARGETS[$i]}"
  echo "==[ Building Rust .so for ${abi} (${target}) ]=="
  ( cd daemon && $CROSS_BIN build --release --target "$target" --features platform-android ) || {
    echo "::warning::Rust build failed for ${abi} — continuing (CI will surface this)"
  }
done

# ── Stage the Rust daemon .so files into the Flutter android jniLibs ─────────
# CoreBridge.kt calls System.loadLibrary("unifiedshield"); the library must be
# present in android/app/src/main/jniLibs/<abi>/ BEFORE `flutter build apk`
# runs, otherwise the universal APK ships without the daemon core.
if [ -d flutter_app ]; then
  FLUTTER_DIR="flutter_app"
elif [ -d flutter ]; then
  FLUTTER_DIR="flutter"
else
  echo "::error::no flutter project directory found"; exit 1
fi

JNILIBS_DIR="${FLUTTER_DIR}/android/app/src/main/jniLibs"
mkdir -p "${JNILIBS_DIR}"
STAGED_ANY=0
for i in "${!ANDROID_ABIS[@]}"; do
  abi="${ANDROID_ABIS[$i]}"
  target="${RUST_TARGETS[$i]}"
  src="daemon/target/${target}/release/libunifiedshield.so"
  if [ -f "$src" ]; then
    mkdir -p "${JNILIBS_DIR}/${abi}"
    cp -v "$src" "${JNILIBS_DIR}/${abi}/libunifiedshield.so"
    STAGED_ANY=1
  else
    echo "::warning::${src} missing — APK will ship without the Rust daemon for ${abi}"
  fi
done
[ "$STAGED_ANY" -eq 1 ] && echo "==[ Staged libunifiedshield.so into ${JNILIBS_DIR} ]=="

# ── Flutter: build universal APK, split-per-ABI APKs, and AAB ────────────────
echo "==[ flutter pub get ]=="
( cd "$FLUTTER_DIR" && flutter pub get )

echo "==[ Build universal APK ]=="
( cd "$FLUTTER_DIR" && flutter build apk --release )
cp -v "$FLUTTER_DIR/build/app/outputs/flutter-apk/app-release.apk" \
   "${REL}/apk/unifiedshield-${VERSION}-enterprise-android-universal.apk" 2>/dev/null || true

echo "==[ Build per-ABI split APKs ]=="
( cd "$FLUTTER_DIR" && flutter build apk --release --split-per-abi )
for abi in "${ANDROID_ABIS[@]}"; do
  src="$FLUTTER_DIR/build/app/outputs/flutter-apk/app-${abi}-release.apk"
  dst="${REL}/apk/unifiedshield-${VERSION}-enterprise-android-${abi}.apk"
  [ -f "$src" ] && cp -v "$src" "$dst" || echo "::warning::$src missing"
done

echo "==[ Build AAB (App Bundle) ]=="
( cd "$FLUTTER_DIR" && flutter build appbundle --release )
cp -v "$FLUTTER_DIR/build/app/outputs/bundle/release/app-release.aab" \
   "${REL}/aab/unifiedshield-${VERSION}-enterprise-android.aab" 2>/dev/null || true

# ── Generate .sha256 siblings ─────────────────────────────────────────────────
( cd "${REL}/apk" && for f in *.apk; do [ -f "$f" ] && sha256sum "$f" > "$f.sha256"; done )
( cd "${REL}/aab" && for f in *.aab; do [ -f "$f" ] && sha256sum "$f" > "$f.sha256"; done )

echo "==[ Android release artifacts ]=="
ls -la "${REL}/apk" "${REL}/aab"
